
[versions]

activityKtx = "1.10.1"
agp = "8.10.1"
androidxActivityCompose = "1.10.1"
androidxAppcompat = "1.7.1"
androidxComposeBom = "2025.06.00"
androidxCoreSplashscreen = "1.0.1"
androidxDatastore = "1.1.7"
androidxLifecycle = "2.9.1"
androidxNavigationCompose = "2.9.0"
androidxRoom = "2.7.1"
androidxSqlite = "2.5.1"
coilCompose = "3.2.0"
desugarJdkLibs = "2.1.5"
detekt = "1.23.8"
koin = "4.1.0"
kotlin = "2.1.20"
kotlinxCoroutines = "1.10.2"
kotlinxSerialization = "1.8.1"
ksp = "2.1.20-2.0.0"
ktor = "3.1.3"
lbAndroidApplication = "1.0.0"
lbAndroidFlavors = "1.0.0"
lbAndroidLibrary = "1.0.0"
lbBom = "4.4.0"
lbDetekt = "1.0.5"
lbMultiplatformLibrary = "0.9.1"
lbResources = "1.0.0"
lbcCore = "1.8.0"
lbcPresenter = "1.4.0"
material3Jvmstubs = "1.4.0-alpha15"
material3alpha="1.4.0-alpha15"
navigationComposeJvmstubs = "2.9.0"
navigationRuntimeAndroid = "2.9.0"
navigationRuntimeJvmstubs = "2.9.0"
skie = "0.10.2-preview.2.1.20"
uiTextGoogleFont="1.8.2"
uiToolingPreviewDesktop = "1.7.0"

[libraries]

activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
androidxActivityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivityCompose" }
androidxAppcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidxComposeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidxComposeFoundation = { group = "androidx.compose.foundation", name = "foundation" }
androidxComposeMaterial3 = { group = "androidx.compose.material3", name = "material3" }
androidxComposeUi = { group = "androidx.compose.ui", name = "ui" }
androidxLifecycleViewModelKtx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidxNavigationCompose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigationCompose" }
androidxRoomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
androidxRoomRuntime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidxSqliteBundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "androidxSqlite" }
composeMaterial3 = {group = "androidx.compose.material3", name = "material3", version.ref="material3alpha"}
desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarJdkLibs" }
detekt = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
gradleAndroid = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
jetbrains-compose-ui-util = { module = "org.jetbrains.compose.ui:ui-util", version = "1.7.1" }
koinAndroid = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koinCore = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koinViewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
kotlinAndroid = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinCompose = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlinxCoroutineBom = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version.ref = "kotlinxCoroutines" }
kotlinxCoroutineCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core" }
kotlinxSerializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

ktorAndroid = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktorIos = { group = "io.ktor", name = "ktor-client-ios", version.ref = "ktor" }

lbAndroidLibraryPlugin = { group = "studio.lunabee.plugins.android.library", name = "studio.lunabee.plugins.android.library.gradle.plugin", version.ref = "lbAndroidLibrary" }
lbBom = { group = "studio.lunabee", name = "lunabee-bom", version.ref = "lbBom" }
lbCore = { group = "studio.lunabee", name = "lbcore" }
lbKtorCore = { group = "studio.lunabee", name = "lbktor-core" }
lbKtorJson = { group = "studio.lunabee", name = "lbktor-json" }
lbKtorKermit = { group = "studio.lunabee", name = "lbktor-kermit" }
lbMultiplatformLibrary = { group = "studio.lunabee.plugins.multiplatform.library", name = "studio.lunabee.plugins.multiplatform.library.gradle.plugin", version.ref = "lbMultiplatformLibrary" }
lbcCore = { group = "studio.lunabee.compose", name = "lbccore", version.ref = "lbcCore" }
lbcPresenter = { group = "studio.lunabee.compose", name = "lbcpresenter", version.ref = "lbcPresenter" }
material3Jvmstubs = { group = "androidx.compose.material3", name = "material3-jvmstubs", version.ref = "material3Jvmstubs" }
navigation-runtime-android = { group = "androidx.navigation", name = "navigation-runtime-android", version.ref = "navigationRuntimeAndroid" }
navigationComposeJvmstubs = { group = "androidx.navigation", name = "navigation-compose-jvmstubs", version.ref = "navigationComposeJvmstubs" }
navigationRuntimeJvmstubs = { group = "androidx.navigation", name = "navigation-runtime-jvmstubs", version.ref = "navigationRuntimeJvmstubs" }
uiTextGoogleFonts = {group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref="uiTextGoogleFont"}
uiToolingPreviewDesktop = { group = "androidx.compose.ui", name = "ui-tooling-preview-desktop", version.ref = "uiToolingPreviewDesktop" }

[plugins]

androidxRoom = { id = "androidx.room", version.ref = "androidxRoom" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
gradleAndroidApplication = { id = "com.android.application", version.ref = "agp" }
gradleAndroidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
lbAndroidApplication = { id = "studio.lunabee.plugins.android.application", version.ref = "lbAndroidApplication" }
lbAndroidFlavors = { id = "studio.lunabee.plugins.android.flavors", version.ref = "lbAndroidFlavors" }
lbAndroidLibrary = { id = "studio.lunabee.plugins.android.library", version.ref = "lbAndroidLibrary" }
lbDetekt = { id = "studio.lunabee.plugins.detekt", version.ref = "lbDetekt" }
lbMultiplatformLibrary = { id = "studio.lunabee.plugins.multiplatform.library", version.ref = "lbMultiplatformLibrary" }
lbResources = { id = "studio.lunabee.plugins.resources", version.ref = "lbResources" }
skie = { id = "co.touchlab.skie", version.ref = "skie" }
